### ISSUE TITLE
How to fit a function I wanted

### ISSUE THREAD

**Issue by Noctise** [WassimTenachi/PhySO#11]
Hi Wassim

 I have a model: log(k)= v*(x1*c1*log(t1)+(1-x1)*c2*log(t2) ) + (1-v)*log(c0*t0)

it’s doesn’t work now, so I wanna build a new function like f(x1,c1*log(t1),c2log(t2)) * log(k) = v*(x1*c1*log(t1)+(1-x1)*c2*log(t2) ) + (1-v)*log(c0*t0)

could I use physo to fit f(x1,c1*log(t1),c2log(t2)) And follow the formula above？

if its ok，how to set the training parameter0.0？

thanks

**Comment by Noctise** [comment]
The variable is v，x1，output is log(k)

**Comment by WassimTenachi** [comment]
Hi @Noctise,

Yes, `physo` is adapted to this type of problem as it can find a free-form symbolic analytical function $f: \mathbb{R}^n \longrightarrow \mathbb{R}$ that fits $y = f(x_0,..., x_n)$ given $(x_0,..., x_n, y)$ data.

Can checkout the getting started tutorial in the readme and tell me if that's answers you question ?

Wassim

**Comment by WassimTenachi** [comment]
Hi @Noctise,
Can you tell me if you were able to follow the getting started tutorial so I can clos the thread ?
Thank you

**Comment by Noctise** [comment]
Hi Wassim

Sorry, I didn't understand the examples in the document. What do x, which is set to [[1,0,0], [1,-1,0]], y, and fixed_consts mean?

These are the parameters I used, but the results were not satisfactoryT_T.

```
expression, logs = physo.SR(X, y,
                            X_names = [ "v"       , "x1"      ],
                            X_units = [ [1, 0, 0] , [1, -1, 0]],
                            y_name  = "K",
                            y_units = [2, -2, 1],
                            fixed_consts       = [ 1.      ],
                            fixed_consts_units = [ [0,0,0] ],
                            free_consts_names = [ "C1log(t1)", "C2log(t2)", "log(c0t0)" ],
                            free_consts_units = [ [0, 0, 1],      , [0, 0, 1],      [0, 0, 1] ],
                            op_names = ["mul", "add", "div", "n2", "sqrt", "exp", "log"],
                            run_config = physo.config.config1.config1                    
)
```

**Comment by WassimTenachi** [comment]
Hi @Noctise,

These are the units of the input variables. Eg:
[1,0,0] is length
[1,-1,0] is length.(time)^(-1) ie a velocity

Do you have physical units in your problem, is x a length or v a velocity for example ?
If it is not the case, you can leave all units arguments to their default values using:

```

expression, logs = physo.SR(X, y,
                            X_names = [ "v"       , "x1"      ],
                            y_name  = "K",
                            fixed_consts       = [ 1.      ],
                            free_consts_names = [ "C1log(t1)", "C2log(t2)", "log(c0t0)" ],
                            op_names = ["mul", "add", "div", "n2", "sqrt", "exp", "log"],
                            run_config = physo.config.config1.config1                    
)

```

Fixed constants are constants which's values are fixed (ie. not adaptative) eg. 1, pi etc they are distinct from free constants eg. c0, c1 which's values are optimised to fits as best as possible X,y given a trial functional form.

**Comment by WassimTenachi** [comment]
Hi @Noctise, did this documentation answer you question ?
Please tell me so I can close this issue.

**Comment by AcrazyQ** [comment]
Hi Wassim
That is your answer "
These are the units of the input variables. Eg:
[1,0,0] is length
[1,-1,0] is length.(time)^(-1) ie a velocity" I had understood,
while I didn't understand the free_consts_units [0,0,1] is mean that the default units?
 
Best wishes and looking forward to your reply.

**Comment by WassimTenachi** [comment]
Arbitrarily considering that the units vector stands for [length, time, mass],
Having a free constants of units [0,0,1] would mean having a free constant mass.

If your problem is not related to physics or physical engineering (where variables and constants have units like length, velocity, mass, temperature etc.) you should simply put every units to [0,0,0] so your data can be treated as dimensionless.

Does that answer your question ?

**Comment by AcrazyQ** [comment]
Hi, Wassim Tecnachi!
1、I saw the describe of&nbsp;physical units in you code(token.py), the set [1,-1,0] represents the velocity, and the unit set is [m,s,kg, and the same]. I don't undestand weather the set [1,-1,0] is the [Displacement,1st order derivative of displacement with respect to time，mass] or not, and I defined an angle phi and set the unit to [0,0,-1], but I don't understand the mean of -1 in this set. I want to calculate the function of Kepler orbital elements evolusion law, it has included some angles, what could I set the units?
2、I readed your paper，and the categorical distribution can be estimated by RNN，but how the physical units prior determined? &nbsp;


Thanks again for your answer! And I look forward to your next reply.

&nbsp;&nbsp;




471349567
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WassimTenachi/PhySO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月3日(星期一) 凌晨5:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WassimTenachi/PhySO] How to fit a function I wanted (Issue #11)





 
Arbitrarily considering that the units vector stands for [length, time, mass],
 Having a free constants of units [0,0,1] would mean having a free constant mass.
 
If your problem is not related to physics or physical engineering (where variables and constants have units like length, velocity, mass, temperature etc.) you should simply put every units to [0,0,0] so your data can be treated as dimensionless.
 
Does that answer your question ?

**Comment by WassimTenachi** [comment]
1. Regarding units, you can choose any convention you like ! You can choose to use units as [length, time, mass...] or [mass, length, time ...], it won't change anything regarding the units analysis performed by physo as long as you use a consistent convention for y, free constants, fixed constants and components of X.
Angles are dimensionless in the context of dimensional analysis so you can put [0,0,0] for your angles.

2. The physical units prior is not learned but determined by our algorithm which performs units analysis following dimensional analysis rules on the fly on equations while they are generated. The details are in algo 1 of the paper:  https://arxiv.org/pdf/2303.03192.pdf with implementation in: physo/physym/dimensional_analysis.py

**Comment by Noctise** [comment]
Hi @WassimTenachi 

I have not yet achieved the desired outcome.
I am currently perusing the source code that you have published and endeavoring to comprehend it, which may require a substantial amount of time.
I will continue to monitor physo, and should any documentation that you produce subsequently prove useful to me, I will persist in my efforts.

By the way, I specialize in the study of chemical materials, and it is possible that some of the parameters may be using outdated units that are no longer applicable to current formulas, leading to dimensional issues.

Lastly, thank you for your response^_^. 
(You may now close this issue)

**Comment by WassimTenachi** [comment]
Ok @Noctise, good luck with that !
I did a bit of chemistry myself, I know that in chemistry proxy units are often used which my lead to inconsistencies for physo.
If you want to understand the method, I recommend looking at files in physym first in that order: token, functions, program, free const, dimensional analysis, execute, prior, reward, dataset and then batch. Unit test can be helpful for understanding too !
Cheers !

**Comment by AcrazyQ** [comment]
Hi，Wassim Tenachi！
Thank you for your previous reply，I have understood your research&nbsp;to a certain extent.


But I have a new problem, how can I solve the problem that the regression of the free constant is not accurate enough, for example, I set a pressure of 101000.00pa, but it only regresses to 100000.00pa.




471349567
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WassimTenachi/PhySO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月7日(星期五) 下午3:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WassimTenachi/PhySO] How to fit a function I wanted (Issue #11)





 
Ok @Noctise, good luck with that !
 I did a bit of chemistry myself, I know that in chemistry proxy units are often used which my lead to inconsistencies for physo.
 If you want to understand the method, I recommend looking at files in physym first in that order: token, functions, program, free const, dimensional analysis, execute, prior, reward, dataset and then batch. Unit test can be helpful for understanding too !
 Cheers !
