### ISSUE TITLE
Custom equations

### ISSUE THREAD

**Issue by biteteemo** [WassimTenachi/PhySO#20]
Hi Wassim, I tried to play your demo by directly changing the mechanical-energy equation in the data points codes:
y_array = m*g*z + m*vz**2 into:
y_array = m*g*z * z/(z+1）+ m*vz**2
I assume the newly added switch function z/(z+1) has no units.

The original equation can be successfully inferred after nine epochs. 
However, for the revised equation, it turned out the PhySO could not get the correct answer even after 4 hours of running.

Should I change other parts of the code if I do the above equation revise?

Thank you!

**Comment by WassimTenachi** [comment]
Hi @biteteemo,

Can you give the script you ran so I can check if it was at all possible to retrieve the equation ?

It sounds like this test case "mgz * z/(z+1）+ mvz**2" might be too hard for the current version of physo at least with the hyperparameters you are using.
If it is not already the case, I suggest you use config1 which is currently the best hyperparameter configuration I have and run it for 1000 epochs.

Keep in mind that SR is intrinsically a very hard problem and that complicated equations might ne be retrieved by physo (at least for now).
When working on a scientifically relevant case, you can try to tune hyperparameters to your own case for best performances.

Wassim

**Comment by biteteemo** [comment]
Hi Wassim, thank you for your response!

I tried with config1 and ran 187 epochs which spent 6 hours last night. The only thing I changed in the code is the equation and run_config = physo.config.config1.config1.

You may check the revised ipynb code here: 
https://github.com/biteteemo/PhySO/blob/main/demo_quick_sr.ipynb

Xu

**Comment by WassimTenachi** [comment]
Here is the data generated with:

```
# Dataset
z = np.random.uniform(-10, 10, 1000)
v = np.random.uniform(-10, 10, 1000)
X = np.stack((z, v), axis=0)
y = 1.234*9.807*z + 1.234*v**2
```

![image](https://user-images.githubusercontent.com/63928316/227466693-1e614b6b-9e99-48ae-aecb-e433d2a9e7bc.png)

An here is the data generated with your code:

```
# Dataset
z = np.random.uniform(-10, 10, 1000)
v = np.random.uniform(-10, 10, 1000)
X = np.stack((z, v), axis=0)
y = 1.234*9.807*z*z/(z+1) + 1.234*v**2
```

![image](https://user-images.githubusercontent.com/63928316/227466842-1d507306-0438-481e-b410-7a0f358363c7.png)

Since phyo is trying to guess the best fitting physical expression having access to this data only, and that the dataset generated using you ranges make the relation much less obvious, it might explain the unability to find the right expression.
You might want to try ranges that makes the data more usable, eg:

```
# Dataset
z = np.random.uniform(-40, 40, 1000)
v = np.random.uniform(-30, 30, 1000)
X = np.stack((z, v), axis=0)
y = 1.234*9.807*z*z/(z+1) + 1.234*v**2
```

Which gives:

![image](https://user-images.githubusercontent.com/63928316/227468556-434d002d-b153-4480-916d-cfecf86c3ef4.png)

And try to run that with config1 for 1000 epochs you can also try multiple runs as the SR process is stochastic.
It might still not be able to resolve your custom problem because SR is intrinsically a very hard problem with a lot of degeneracies and that config1 hyperparameters are not necessarily the best ones (I'm working on a more capable config2).
