### ISSUE TITLE
Very slow on cuda

### ISSUE THREAD

**Issue by swang066** [WassimTenachi/PhySO#7]
Hi Wassim,

I am trying to use the PhySO on the Colab. But I found it is very slow when I run the Demo on the gpu cuda, which is even slower than the cpu (~60s/epoch on cpu vs. ~170s/epoch on gpu). Did you test the gpu version? Is it also slow?

Thank you,

Song

**Comment by feevos** [comment]
Hi, thank you for your interest in our work (am co-author of the paper). This is normal, because the LSTM is very light, so you don't need cuda to run it. You spend more time copying data than actually optimizing. If you want to see performance gain with cuda, you need to modify the LSTM network (number of features, etc).

**Comment by swang066** [comment]
Hi Foivos, thank you very much! Another question is whether PhySO can handle more variables? For example, I have 12 variables (some of them might be extra variables, which are not associated with target), 1 target, and 2000 samples. Can it find a formula between variables and target? If so, will it take a very long time? Thank you!

**Comment by WassimTenachi** [comment]
Please let us know if everything is working out for you on the technical aspect so we can close this issue.
If you're using PhySO for research please let us know if it suits your needs ! :)
